# Generated by Django 5.1.2 on 2024-11-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('editora', models.CharField(max_length=255)),
                ('ano_publicacao', models.PositiveIntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('quantidade_total', models.PositiveIntegerField()),
                ('quantidade_disponivel', models.PositiveIntegerField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
